language: csharp
solution: MyGame.sln
install: 
- nuget restore MyGame.sln
- nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script: 
- xbuild ./MyGame.sln
- nunit-console ./MyGame.sln
notifications:
  slack: dp1-2015s2:b1lqOF67qvXUgK1Pyn5w4mfM